### ISSUE TITLE
Action breaks on macos-11

### ISSUE THREAD

**Issue by kclejeune** [cachix/install-nix-action#102]
Github Actions has recently switched the default `macos-latest` runners to use `macos-11` rather than the previous `macos-10.15`. This appears to have broken the installer action (based on my repo https://github.com/kclejeune/system/runs/3935328648). 

Relevant logs are pasted below, let me know if I can provide any additional information!

```
2021-10-19T05:55:12.6670340Z Found online and idle hosted runner in the current repository's organization account that matches the required labels: 'macos-latest'
2021-10-19T05:55:12.8026506Z Waiting for a Hosted runner in the 'organization' to pick this job...
2021-10-19T05:55:12.9812753Z Job is waiting for a hosted runner to come online.
2021-10-19T05:55:22.2235054Z Job is about to start running on the hosted runner: GitHub Actions 2 (hosted)
2021-10-19T05:55:25.2772430Z Current runner version: '2.283.2'
2021-10-19T05:55:25.2822640Z ##[group]Operating System
2021-10-19T05:55:25.2823740Z macOS
2021-10-19T05:55:25.2824180Z 11.6
2021-10-19T05:55:25.2824640Z 20G165
2021-10-19T05:55:25.2825090Z ##[endgroup]
2021-10-19T05:55:25.2825780Z ##[group]Virtual Environment
2021-10-19T05:55:25.2826460Z Environment: macos-11
2021-10-19T05:55:25.2826970Z Version: 20211011.3
2021-10-19T05:55:25.2827960Z Included Software: https://github.com/actions/virtual-environments/blob/macOS-11/20211011.3/images/macos/macos-11-Readme.md
2021-10-19T05:55:25.2829310Z Image Release: https://github.com/actions/virtual-environments/releases/tag/macOS-11%2F20211011.3
2021-10-19T05:55:25.2831170Z ##[endgroup]
2021-10-19T05:55:25.2832030Z ##[group]Virtual Environment Provisioner
2021-10-19T05:55:25.2832710Z 1.0.0.0-master-20211007-1
2021-10-19T05:55:25.2833210Z ##[endgroup]
2021-10-19T05:55:25.2835470Z ##[group]GITHUB_TOKEN Permissions
2021-10-19T05:55:25.2836950Z Actions: write
2021-10-19T05:55:25.2837660Z Checks: write
2021-10-19T05:55:25.2838250Z Contents: write
2021-10-19T05:55:25.2838910Z Deployments: write
2021-10-19T05:55:25.2839490Z Discussions: write
2021-10-19T05:55:25.2839980Z Issues: write
2021-10-19T05:55:25.2840510Z Metadata: read
2021-10-19T05:55:25.2841000Z Packages: write
2021-10-19T05:55:25.2841840Z Pages: write
2021-10-19T05:55:25.2842610Z PullRequests: write
2021-10-19T05:55:25.2843220Z RepositoryProjects: write
2021-10-19T05:55:25.2844190Z SecurityEvents: write
2021-10-19T05:55:25.2844780Z Statuses: write
2021-10-19T05:55:25.2845530Z ##[endgroup]
2021-10-19T05:55:25.2849460Z Prepare workflow directory
2021-10-19T05:55:25.3681130Z Prepare all required actions
2021-10-19T05:55:25.3693050Z Getting action download info
2021-10-19T05:55:25.6386000Z Download action repository 'actions/checkout@v2.3.4' (SHA:5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f)
2021-10-19T05:55:27.6324100Z Download action repository 'cachix/install-nix-action@v14' (SHA:11e5400eccd6f89582f7da71e36b86e2b0924252)
2021-10-19T05:55:28.0515860Z Download action repository 'cachix/cachix-action@v10' (SHA:73e75d1a0cd4330597a571e8f9dedb41faa2fc4e)
2021-10-19T05:55:28.8656790Z ##[group]Run actions/checkout@v2.3.4
# actions/checkout logs omitted
2021-10-19T05:55:31.0554520Z ##[group]Run cachix/install-nix-action@v14
2021-10-19T05:55:31.0555070Z with:
2021-10-19T05:55:31.0555880Z   install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.4pre20210823_af94b54/install
2021-10-19T05:55:31.0557760Z   extra_nix_config: experimental-features = nix-command flakes
access-tokens = github.com=***

2021-10-19T05:55:31.0558940Z env:
2021-10-19T05:55:31.0559360Z   NIX_VERSION: nix-2.4pre20210823_af94b54
2021-10-19T05:55:31.0559800Z ##[endgroup]
2021-10-19T05:55:32.3701510Z installer options: --no-channel-add --darwin-use-unencrypted-nix-store-volume --nix-extra-conf-file /tmp/nix.conf --daemon --daemon-user-count 6
2021-10-19T05:55:32.8878680Z   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2021-10-19T05:55:32.8881090Z                                  Dload  Upload   Total   Spent    Left  Speed
2021-10-19T05:55:32.8882450Z
2021-10-19T05:55:33.0697960Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2021-10-19T05:55:33.0700880Z 100   615  100   615    0     0   3234      0 --:--:-- --:--:-- --:--:--  3397
2021-10-19T05:55:33.1911470Z
2021-10-19T05:55:33.1915800Z 100  4061  100  4061    0     0  13024      0 --:--:-- --:--:-- --:--:-- 13024
2021-10-19T05:55:33.2150650Z downloading Nix 2.4pre20210823_af94b54 binary tarball for x86_64-darwin from 'https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.4pre20210823_af94b54/nix-2.4pre20210823_af94b54-x86_64-darwin.tar.xz' to '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/nix-binary-tarball-unpack.XXXXXXXXXX.fBgBLpKe'...
2021-10-19T05:55:33.2336900Z   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2021-10-19T05:55:33.2339740Z                                  Dload  Upload   Total   Spent    Left  Speed
2021-10-19T05:55:33.2343550Z
2021-10-19T05:55:33.4147600Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2021-10-19T05:55:33.4149620Z 100   655  100   655    0     0   3517      0 --:--:-- --:--:-- --:--:--  3618
2021-10-19T05:55:33.6229340Z
2021-10-19T05:55:34.5000110Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2021-10-19T05:55:34.5001870Z 100 33.3M  100 33.3M    0     0  26.2M      0  0:00:01  0:00:01 --:--:-- 38.0M
2021-10-19T05:55:39.0667790Z Warning: the flag --darwin-use-unencrypted-nix-store-volume
2021-10-19T05:55:39.0695010Z          is no longer needed and will be removed in the future.
2021-10-19T05:55:39.0695940Z
2021-10-19T05:55:39.0709690Z [1;31mSwitching to the Multi-user Installer[0m
2021-10-19T05:55:39.3094640Z [32mWelcome to the Multi-User Nix Installation
2021-10-19T05:55:39.3126860Z [0m
2021-10-19T05:55:39.3127710Z This installation tool will set up your computer with the Nix package
2021-10-19T05:55:39.3128410Z manager. This will happen in a few stages:
2021-10-19T05:55:39.3128790Z
2021-10-19T05:55:39.3129970Z 1. Make sure your computer doesn't already have Nix. If it does, I
2021-10-19T05:55:39.3130720Z    will show you instructions on how to clean up your old install.
2021-10-19T05:55:39.3131330Z
2021-10-19T05:55:39.3131910Z 2. Show you what we are going to install and where. Then we will ask
2021-10-19T05:55:39.3132500Z    if you are ready to continue.
2021-10-19T05:55:39.3132840Z
2021-10-19T05:55:39.3133400Z 3. Create the system users and groups that the Nix daemon uses to run
2021-10-19T05:55:39.3134140Z    builds.
2021-10-19T05:55:39.3134380Z
2021-10-19T05:55:39.3134940Z 4. Perform the basic installation of the Nix files daemon.
2021-10-19T05:55:39.3135370Z
2021-10-19T05:55:39.3135940Z 5. Configure your shell to import special Nix Profile files, so you
2021-10-19T05:55:39.3136490Z    can use Nix.
2021-10-19T05:55:39.3136860Z
2021-10-19T05:55:39.3137450Z 6. Start the Nix daemon.
2021-10-19T05:55:39.3137720Z
2021-10-19T05:55:39.3138820Z [32m[4;32mWould you like to see a more detailed list of what we will do?
2021-10-19T05:55:39.3139890Z [0mNo TTY, assuming you would say yes :)
2021-10-19T05:55:39.3159860Z
2021-10-19T05:55:39.3160550Z We will:
2021-10-19T05:55:39.3160850Z
2021-10-19T05:55:39.3161940Z  - make sure your computer doesn't already have Nix files
2021-10-19T05:55:39.3162630Z    (if it does, I will tell you how to clean them up.)
2021-10-19T05:55:39.3163720Z  - create local users (see the list above for the users we'll make)
2021-10-19T05:55:39.3165430Z  - create a local group (nixbld)
2021-10-19T05:55:39.3166330Z  - install Nix in to /nix
2021-10-19T05:55:39.3167320Z  - create a configuration file in /etc/nix
2021-10-19T05:55:39.3168480Z  - set up the "default profile" by creating some Nix-related files in
2021-10-19T05:55:39.3169060Z    /var/root
2021-10-19T05:55:39.3190620Z  - back up /etc/bashrc to /etc/bashrc.backup-before-nix
2021-10-19T05:55:39.3191940Z  - update /etc/bashrc to include some Nix configuration
2021-10-19T05:55:39.3195270Z  - create a Nix volume and a LaunchDaemon to mount it
2021-10-19T05:55:39.3196770Z  - create a LaunchDaemon (at /Library/LaunchDaemons/org.nixos.nix-daemon.plist) for nix-daemon
2021-10-19T05:55:39.3197460Z
2021-10-19T05:55:39.3198430Z [32m[4;32mReady to continue?
2021-10-19T05:55:39.3199410Z [0mNo TTY, assuming you would say yes :)
2021-10-19T05:55:39.3273440Z
2021-10-19T05:55:39.3274990Z [34m---- let's talk about sudo -----------------------------------------------------
2021-10-19T05:55:39.3303270Z [0mThis script is going to call sudo a lot. Normally, it would show you
2021-10-19T05:55:39.3304110Z exactly what commands it is running and why. However, the script is
2021-10-19T05:55:39.3304960Z run in a headless fashion, like this:
2021-10-19T05:55:39.3305320Z
2021-10-19T05:55:39.3306250Z   $ curl -L https://nixos.org/nix/install | sh
2021-10-19T05:55:39.3306820Z
2021-10-19T05:55:39.3307800Z or maybe in a CI pipeline. Because of that, we're going to skip the
2021-10-19T05:55:39.3308640Z verbose output in the interest of brevity.
2021-10-19T05:55:39.3309000Z
2021-10-19T05:55:39.3309410Z If you would like to
2021-10-19T05:55:39.3309920Z see the output, try like this:
2021-10-19T05:55:39.3310260Z
2021-10-19T05:55:39.3311250Z   $ curl -L -o install-nix https://nixos.org/nix/install
2021-10-19T05:55:39.3312380Z   $ sh ./install-nix
2021-10-19T05:55:39.3312700Z
2021-10-19T05:55:39.3312980Z
2021-10-19T05:55:39.3313860Z [32m~~> Fixing any leftover Nix volume state
2021-10-19T05:55:39.3335210Z [0mBefore I try to install, I'll check for any existing Nix volume config
2021-10-19T05:55:39.3336370Z and ask for your permission to remove it (so that the installer can
2021-10-19T05:55:39.3337770Z start fresh). I'll also ask for permission to fix any issues I spot.
2021-10-19T05:55:39.3676260Z
2021-10-19T05:55:39.3678130Z [34m---- Nix config report ---------------------------------------------------------
2021-10-19T05:55:39.3679570Z [0m[1m        Temp Dir[0m:	/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp.kkkxP5kAlm
2021-10-19T05:55:39.3680630Z [1m        Nix Root[0m:	/nix
2021-10-19T05:55:39.3681650Z [1m     Build Users[0m:	6
2021-10-19T05:55:39.3682470Z [1m  Build Group ID[0m:	30000
2021-10-19T05:55:39.3683400Z [1mBuild Group Name[0m:	nixbld
2021-10-19T05:55:39.3683770Z
2021-10-19T05:55:39.3684560Z [4;34mbuild users:
2021-10-19T05:55:39.3685480Z [0m[1m    Username[0m:	UID
2021-10-19T05:55:39.3756890Z [1m     _nixbld1[0m:	301
2021-10-19T05:55:39.3777670Z [1m     _nixbld2[0m:	302
2021-10-19T05:55:39.3798420Z [1m     _nixbld3[0m:	303
2021-10-19T05:55:39.3819410Z [1m     _nixbld4[0m:	304
2021-10-19T05:55:39.3840240Z [1m     _nixbld5[0m:	305
2021-10-19T05:55:39.3861120Z [1m     _nixbld6[0m:	306
2021-10-19T05:55:39.3861450Z
2021-10-19T05:55:39.3862500Z [32m[4;32mReady to continue?
2021-10-19T05:55:39.3863490Z [0mNo TTY, assuming you would say yes :)
2021-10-19T05:55:39.3900660Z
2021-10-19T05:55:39.3902370Z [34m---- Preparing a Nix volume ----------------------------------------------------
2021-10-19T05:55:39.3930370Z [0m    Nix traditionally stores its data in the root directory /nix, but
2021-10-19T05:55:39.3932140Z     macOS now (starting in 10.15 Catalina) has a read-only root directory.
2021-10-19T05:55:39.3932980Z     To support Nix, I will create a volume and configure macOS to mount it
2021-10-19T05:55:39.3933730Z     at /nix.
2021-10-19T05:55:39.3962360Z
2021-10-19T05:55:39.3963930Z [32m~~> Configuring /etc/synthetic.conf to make a mount-point at /nix
2021-10-19T05:55:39.5364790Z [0m
2021-10-19T05:55:39.5365990Z [32m~~> Creating a Nix volume
2021-10-19T05:55:40.3728370Z [0m
2021-10-19T05:55:40.3731000Z [32m~~> Configuring /etc/fstab to specify volume mount options
2021-10-19T05:55:40.4841320Z [0m
2021-10-19T05:55:40.4843570Z [32m~~> Configuring LaunchDaemon to mount 'Nix Store'
2021-10-19T05:55:51.0234130Z
2021-10-19T05:55:51.0236960Z [32m~~> Setting up the build group nixbld
2021-10-19T05:55:51.0918550Z [0m[1m            Created[0m:	Yes
2021-10-19T05:55:51.0971260Z
2021-10-19T05:55:51.0979180Z [32m~~> Setting up the build user _nixbld1
2021-10-19T05:55:51.2124510Z [0m[1m           Created[0m:	Yes
2021-10-19T05:55:51.2936600Z [1m            Hidden[0m:	Yes
2021-10-19T05:55:51.3766090Z [1m    Home Directory[0m:	/var/empty
2021-10-19T05:55:51.3973780Z [1m              Note[0m:	Nix build user 1
2021-10-19T05:55:51.4727300Z [1m   Logins Disabled[0m:	Yes
2021-10-19T05:55:51.5340430Z [1m  Member of nixbld[0m:	Yes
2021-10-19T05:55:51.6194730Z [1m    PrimaryGroupID[0m:	30000
2021-10-19T05:55:51.6218420Z
2021-10-19T05:55:51.6220800Z [32m~~> Setting up the build user _nixbld2
2021-10-19T05:55:51.6976290Z [0m[1m           Created[0m:	Yes
2021-10-19T05:55:51.7753910Z [1m            Hidden[0m:	Yes
2021-10-19T05:55:51.8532960Z [1m    Home Directory[0m:	/var/empty
2021-10-19T05:55:51.8704840Z [1m              Note[0m:	Nix build user 2
2021-10-19T05:55:51.9492310Z [1m   Logins Disabled[0m:	Yes
2021-10-19T05:55:52.0062890Z [1m  Member of nixbld[0m:	Yes
2021-10-19T05:55:52.0910920Z [1m    PrimaryGroupID[0m:	30000
2021-10-19T05:55:52.0934330Z
2021-10-19T05:55:52.0935710Z [32m~~> Setting up the build user _nixbld3
2021-10-19T05:55:52.1690440Z [0m[1m           Created[0m:	Yes
2021-10-19T05:55:52.2475270Z [1m            Hidden[0m:	Yes
2021-10-19T05:55:52.3296230Z [1m    Home Directory[0m:	/var/empty
2021-10-19T05:55:52.3476880Z [1m              Note[0m:	Nix build user 3
2021-10-19T05:55:52.4270970Z [1m   Logins Disabled[0m:	Yes
2021-10-19T05:55:52.4887790Z [1m  Member of nixbld[0m:	Yes
2021-10-19T05:55:52.5782800Z [1m    PrimaryGroupID[0m:	30000
2021-10-19T05:55:52.5806380Z
2021-10-19T05:55:52.5808040Z [32m~~> Setting up the build user _nixbld4
2021-10-19T05:55:52.6590160Z [0m[1m           Created[0m:	Yes
2021-10-19T05:55:52.7375380Z [1m            Hidden[0m:	Yes
2021-10-19T05:55:52.8155170Z [1m    Home Directory[0m:	/var/empty
2021-10-19T05:55:52.8332290Z [1m              Note[0m:	Nix build user 4
2021-10-19T05:55:52.9096470Z [1m   Logins Disabled[0m:	Yes
2021-10-19T05:55:52.9682350Z [1m  Member of nixbld[0m:	Yes
2021-10-19T05:55:53.0522190Z [1m    PrimaryGroupID[0m:	30000
2021-10-19T05:55:53.0544710Z
2021-10-19T05:55:53.0546600Z [32m~~> Setting up the build user _nixbld5
2021-10-19T05:55:53.1296710Z [0m[1m           Created[0m:	Yes
2021-10-19T05:55:53.2063980Z [1m            Hidden[0m:	Yes
2021-10-19T05:55:53.2838550Z [1m    Home Directory[0m:	/var/empty
2021-10-19T05:55:53.3016180Z [1m              Note[0m:	Nix build user 5
2021-10-19T05:55:53.3779370Z [1m   Logins Disabled[0m:	Yes
2021-10-19T05:55:53.4351520Z [1m  Member of nixbld[0m:	Yes
2021-10-19T05:55:53.5200190Z [1m    PrimaryGroupID[0m:	30000
2021-10-19T05:55:53.5222590Z
2021-10-19T05:55:53.5224680Z [32m~~> Setting up the build user _nixbld6
2021-10-19T05:55:53.6030210Z [0m[1m           Created[0m:	Yes
2021-10-19T05:55:53.6812610Z [1m            Hidden[0m:	Yes
2021-10-19T05:55:53.7602370Z [1m    Home Directory[0m:	/var/empty
2021-10-19T05:55:53.7780570Z [1m              Note[0m:	Nix build user 6
2021-10-19T05:55:53.8547570Z [1m   Logins Disabled[0m:	Yes
2021-10-19T05:55:53.9133100Z [1m  Member of nixbld[0m:	Yes
2021-10-19T05:55:53.9967180Z [1m    PrimaryGroupID[0m:	30000
2021-10-19T05:55:53.9967600Z
2021-10-19T05:55:53.9968850Z [32m~~> Setting up the basic directory structure
2021-10-19T05:55:54.0781480Z [0minstall: mkdir /nix/var
2021-10-19T05:55:54.0782200Z install: mkdir /nix/var/log
2021-10-19T05:55:54.0783430Z install: mkdir /nix/var/log/nix
2021-10-19T05:55:54.0783920Z install: mkdir /nix/var/log/nix/drvs
2021-10-19T05:55:54.0784430Z install: mkdir /nix/var/nix
2021-10-19T05:55:54.0784930Z install: mkdir /nix/var/nix/db
2021-10-19T05:55:54.0785400Z install: mkdir /nix/var/nix/gcroots
2021-10-19T05:55:54.0786200Z install: mkdir /nix/var/nix/profiles
2021-10-19T05:55:54.0787110Z install: mkdir /nix/var/nix/temproots
2021-10-19T05:55:54.0787620Z install: mkdir /nix/var/nix/userpool
2021-10-19T05:55:54.0788720Z install: mkdir /nix/var/nix/gcroots/per-user
2021-10-19T05:55:54.0789750Z install: mkdir /nix/var/nix/profiles/per-user
2021-10-19T05:55:54.1096440Z install: mkdir /nix/store
2021-10-19T05:55:54.1397660Z install: mkdir /etc/nix
2021-10-19T05:55:54.1410400Z
2021-10-19T05:55:54.1411850Z [32m~~> Installing Nix
2021-10-19T05:55:58.5450320Z [0m      Alright! We have our first nix at /nix/store/sgr7088amn2kdiq7rnm8dw2gwx4rb0pw-nix-2.4pre20210823_af94b54
2021-10-19T05:56:02.6193640Z       Just finished getting the nix database ready.
2021-10-19T05:56:02.6197460Z
2021-10-19T05:56:02.6201130Z [32m~~> Setting up shell profiles: /etc/bashrc /etc/profile.d/nix.sh /etc/zshenv /etc/bash.bashrc /etc/zsh/zshenv
2021-10-19T05:56:02.7120410Z [0m
2021-10-19T05:56:02.7130310Z # Nix
2021-10-19T05:56:02.7131820Z if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
2021-10-19T05:56:02.7134780Z   . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
2021-10-19T05:56:02.7157870Z fi
2021-10-19T05:56:02.7169110Z # End Nix
2021-10-19T05:56:02.7184980Z
2021-10-19T05:56:02.8005250Z
2021-10-19T05:56:02.8006550Z # Nix
2021-10-19T05:56:02.8008440Z if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
2021-10-19T05:56:02.8010490Z   . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
2021-10-19T05:56:02.8011090Z fi
2021-10-19T05:56:02.8011420Z # End Nix
2021-10-19T05:56:02.8011640Z
2021-10-19T05:56:02.9344270Z
2021-10-19T05:56:02.9446350Z # Nix
2021-10-19T05:56:02.9548710Z if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
2021-10-19T05:56:02.9593520Z   . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
2021-10-19T05:56:02.9603300Z fi
2021-10-19T05:56:02.9664970Z # End Nix
2021-10-19T05:56:02.9675430Z
2021-10-19T05:56:02.9806700Z
2021-10-19T05:56:02.9910080Z [32m~~> Setting up the default profile
2021-10-19T05:56:03.1714740Z [0minstalling 'nix-2.4pre20210823_af94b54'
2021-10-19T05:56:03.5875090Z building '/nix/store/l04ia1g95p06jllifg3a1947hcvy1zyg-user-environment.drv'...
2021-10-19T05:56:03.8600850Z installing 'nss-cacert-3.66'
2021-10-19T05:56:04.0751860Z building '/nix/store/1f1wmqf69p3k0grnzh517af140vlv1xy-user-environment.drv'...
2021-10-19T05:56:04.2062230Z [0m
2021-10-19T05:56:04.2063780Z [32m~~> Setting up the nix-daemon LaunchDaemon
2021-10-19T05:56:14.3516130Z [0m[32mAlright! We're done!
2021-10-19T05:56:14.4001610Z [0mTry it! Open a new terminal, and type:
2021-10-19T05:56:14.4002130Z
2021-10-19T05:56:14.4003410Z   $ nix-shell -p nix-info --run "nix-info -m"
2021-10-19T05:56:14.4004110Z
2021-10-19T05:56:14.4004720Z Thank you for using this installer. If you have any feedback or need
2021-10-19T05:56:14.4005730Z help, don't hesitate:
2021-10-19T05:56:14.4006010Z
2021-10-19T05:56:14.4006670Z You can open an issue at https://github.com/nixos/nix/issues
2021-10-19T05:56:14.4007120Z
2021-10-19T05:56:14.4007490Z Or feel free to contact the team:
2021-10-19T05:56:14.4008330Z  - Matrix: #nix:nixos.org
2021-10-19T05:56:14.4009200Z  - IRC: in #nixos on irc.libera.chat
2021-10-19T05:56:14.4010020Z  - twitter: @nixos_org
2021-10-19T05:56:14.4011440Z  - forum: https://discourse.nixos.org
2021-10-19T05:56:14.4049250Z
2021-10-19T05:56:14.4051210Z [34m---- Reminders -----------------------------------------------------------------
2021-10-19T05:56:14.4052390Z [0m[34m[ 1 ][0m
2021-10-19T05:56:14.4053300Z Nix won't work in active shell sessions until you restart them.
2021-10-19T05:56:14.4054060Z
2021-10-19T05:56:14.9975560Z /nix:
2021-10-19T05:56:14.9979870Z Error: unable to perform operation.  (-400)
2021-10-19T05:56:14.9980420Z 	Error: unknown indexing state.
2021-10-19T05:56:15.0031730Z child_process.js:642
2021-10-19T05:56:15.0033620Z     throw err;
2021-10-19T05:56:15.0034040Z     ^
2021-10-19T05:56:15.0034250Z
2021-10-19T05:56:15.0035630Z Error: Command failed: /Users/runner/work/_actions/cachix/install-nix-action/v14/lib/install-nix.sh
2021-10-19T05:56:15.0036470Z     at checkExecSyncError (child_process.js:621:11)
2021-10-19T05:56:15.0037140Z     at Object.execFileSync (child_process.js:639:15)
2021-10-19T05:56:15.0038430Z     at Object.<anonymous> (/Users/runner/work/_actions/cachix/install-nix-action/v14/lib/main.js:4:17)
2021-10-19T05:56:15.0039240Z     at Module._compile (internal/modules/cjs/loader.js:959:30)
2021-10-19T05:56:15.0039980Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
2021-10-19T05:56:15.0040690Z     at Module.load (internal/modules/cjs/loader.js:815:32)
2021-10-19T05:56:15.0041370Z     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
2021-10-19T05:56:15.0042150Z     at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
2021-10-19T05:56:15.0060090Z     at internal/main/run_main_module.js:17:11 {
2021-10-19T05:56:15.0060540Z   status: 1,
2021-10-19T05:56:15.0060870Z   signal: null,
2021-10-19T05:56:15.0061250Z   output: [ null, null, null ],
2021-10-19T05:56:15.0061620Z   pid: 961,
2021-10-19T05:56:15.0061940Z   stdout: null,
2021-10-19T05:56:15.0062290Z   stderr: null
2021-10-19T05:56:15.0062580Z }
2021-10-19T05:56:15.1014150Z Post job cleanup.
2021-10-19T05:56:15.2389720Z [command]/usr/local/bin/git version
2021-10-19T05:56:15.2471520Z git version 2.33.0
2021-10-19T05:56:15.2526940Z [command]/usr/local/bin/git config --local --name-only --get-regexp core\.sshCommand
2021-10-19T05:56:15.2610020Z [command]/usr/local/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2021-10-19T05:56:15.3644030Z [command]/usr/local/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2021-10-19T05:56:15.3714650Z http.https://github.com/.extraheader
2021-10-19T05:56:15.3731520Z [command]/usr/local/bin/git config --local --unset-all http.https://github.com/.extraheader
2021-10-19T05:56:15.4240630Z [command]/usr/local/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2021-10-19T05:56:15.5722380Z Cleaning up orphan processes
```

**Comment by kclejeune** [comment]
@domenkozar yep, that worked. I assumed dependabot would've updated that so I didn't catch that, thanks!
