### ISSUE TITLE
Self-hosted runner running as root

### ISSUE THREAD

**Issue by kubukoz** [cachix/install-nix-action#119]
Hi! I have a self-hosted runner which doesn't use docker to run actions. If I just add the action, the installer complains that I'm running it as root. What's the recommended way to get Nix installed in this case?

**Comment by domenkozar** [comment]
Can't you run github runner as non-root?

**Comment by kubukoz** [comment]
I don't have a choice, it's predefined on a per-organization basis in our company.

**Comment by domenkozar** [comment]
That's more a Nix installer issue: https://github.com/NixOS/nix/issues/936

**Comment by domenkozar** [comment]
Could you post the log for future reference?

**Comment by kubukoz** [comment]
Sorry for the delay.

<details>
<summary>logs</summary>

```
2022-01-31T12:02:16.4851807Z ##[section]Starting: Request a runner to run this job
2022-01-31T12:02:16.5654199Z Can't find any online and idle self-hosted runner in current repository that matches the required labels: 'self-hosted'
2022-01-31T12:02:16.7009669Z Found online and idle self-hosted runner in current repository's organization/enterprise account that matches the required labels: 'self-hosted'
2022-01-31T12:02:16.9231818Z ##[section]Finishing: Request a runner to run this job
2022-01-31T12:02:21.1610911Z Current runner version: '2.273.5'
2022-01-31T12:02:21.1614238Z Runner name: '0df3c58fddaf4f2f7-1'
2022-01-31T12:02:21.1615295Z Machine name: 'ip-10-195-81-132'
2022-01-31T12:02:21.1617483Z Prepare workflow directory
2022-01-31T12:02:21.1776497Z Prepare all required actions
2022-01-31T12:02:21.1785113Z Getting action download info
2022-01-31T12:02:21.8953949Z Download action repository 'actions/checkout@v2.3.4'
2022-01-31T12:02:22.0395494Z Download action repository 'cachix/install-nix-action@v16'
2022-01-31T12:02:22.2616822Z ##[group]Run actions/checkout@v2.3.4
2022-01-31T12:02:22.2617327Z with:
2022-01-31T12:02:22.2617805Z   repository: services-commons/nix-ds
2022-01-31T12:02:22.2618526Z   token: ***
2022-01-31T12:02:22.2618831Z   ssh-strict: true
2022-01-31T12:02:22.2619207Z   persist-credentials: true
2022-01-31T12:02:22.2619584Z   clean: true
2022-01-31T12:02:22.2619890Z   fetch-depth: 1
2022-01-31T12:02:22.2620182Z   lfs: false
2022-01-31T12:02:22.2620484Z   submodules: false
2022-01-31T12:02:22.2620827Z ##[endgroup]
2022-01-31T12:02:22.3551671Z Syncing repository: services-commons/nix-ds
2022-01-31T12:02:22.3552592Z ##[group]Getting Git version info
2022-01-31T12:02:22.3553873Z Working directory is '/opt/agent/runners/0df3c58fddaf4f2f7-1/_work/nix-ds/nix-ds'
2022-01-31T12:02:22.3554913Z [command]/usr/bin/git version
2022-01-31T12:02:22.3567395Z git version 2.32.0
2022-01-31T12:02:22.3586760Z ##[endgroup]
2022-01-31T12:02:22.3594724Z [command]/usr/bin/git config --local --get remote.origin.url
2022-01-31T12:02:22.3617161Z <hidden>
2022-01-31T12:02:22.3626906Z ##[group]Removing previously created refs, to avoid conflicts
2022-01-31T12:02:22.3631128Z [command]/usr/bin/git rev-parse --symbolic-full-name --verify --quiet HEAD
2022-01-31T12:02:22.3651783Z refs/heads/main
2022-01-31T12:02:22.3658247Z [command]/usr/bin/git checkout --detach
2022-01-31T12:02:22.3689800Z HEAD is now at 5514fa6 Use unstable nixpkgs for good measure
2022-01-31T12:02:22.3696414Z [command]/usr/bin/git rev-parse --symbolic-full-name --branches
2022-01-31T12:02:22.3718093Z refs/heads/main
2022-01-31T12:02:22.3724128Z [command]/usr/bin/git branch --delete --force main
2022-01-31T12:02:22.3750595Z Deleted branch main (was 5514fa6).
2022-01-31T12:02:22.3755773Z [command]/usr/bin/git rev-parse --symbolic-full-name --remotes=origin
2022-01-31T12:02:22.3776304Z refs/remotes/origin/ci
2022-01-31T12:02:22.3776664Z refs/remotes/origin/main
2022-01-31T12:02:22.3779644Z ##[endgroup]
2022-01-31T12:02:22.3780070Z ##[group]Cleaning the repository
2022-01-31T12:02:22.3783602Z [command]/usr/bin/git clean -ffdx
2022-01-31T12:02:22.3810767Z [command]/usr/bin/git reset --hard HEAD
2022-01-31T12:02:22.3840038Z HEAD is now at 5514fa6 Use unstable nixpkgs for good measure
2022-01-31T12:02:22.3843664Z ##[endgroup]
2022-01-31T12:02:22.3845664Z ##[group]Disabling automatic garbage collection
2022-01-31T12:02:22.3849805Z [command]/usr/bin/git config --local gc.auto 0
2022-01-31T12:02:22.3873735Z ##[endgroup]
2022-01-31T12:02:22.3879215Z ##[group]Setting up auth
2022-01-31T12:02:22.3904183Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2022-01-31T12:02:22.3931987Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2022-01-31T12:02:22.4212451Z [command]/usr/bin/git config --local --name-only --get-regexp <hidden>
2022-01-31T12:02:22.4242664Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp '<hidden>' && git config --local --unset-all <hidden> || :
2022-01-31T12:02:22.4523038Z [command]/usr/bin/git config --local <hidden> AUTHORIZATION: basic ***
2022-01-31T12:02:22.4571353Z ##[endgroup]
2022-01-31T12:02:22.4571875Z ##[group]Fetching the repository
2022-01-31T12:02:22.4578924Z [command]/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +aafc6bf1ec658daaee9a4c186a4358c57e3e425b:refs/remotes/origin/ci
2022-01-31T12:02:22.7457154Z remote: Enumerating objects: 13, done.        
2022-01-31T12:02:22.7470279Z remote: Counting objects:   7% (1/13)        
2022-01-31T12:02:22.7472926Z remote: Counting objects:  15% (2/13)        
2022-01-31T12:02:22.7474584Z remote: Counting objects:  23% (3/13)        
2022-01-31T12:02:22.7476693Z remote: Counting objects:  30% (4/13)        
2022-01-31T12:02:22.7478399Z remote: Counting objects:  38% (5/13)        
2022-01-31T12:02:22.7479982Z remote: Counting objects:  46% (6/13)        
2022-01-31T12:02:22.7481550Z remote: Counting objects:  53% (7/13)        
2022-01-31T12:02:22.7483011Z remote: Counting objects:  61% (8/13)        
2022-01-31T12:02:22.7484407Z remote: Counting objects:  69% (9/13)        
2022-01-31T12:02:22.7485830Z remote: Counting objects:  76% (10/13)        
2022-01-31T12:02:22.7487292Z remote: Counting objects:  84% (11/13)        
2022-01-31T12:02:22.7488787Z remote: Counting objects:  92% (12/13)        
2022-01-31T12:02:22.7490259Z remote: Counting objects: 100% (13/13)        
2022-01-31T12:02:22.7491274Z remote: Counting objects: 100% (13/13), done.        
2022-01-31T12:02:22.7492182Z remote: Compressing objects:  50% (1/2)        
2022-01-31T12:02:22.7493125Z remote: Compressing objects: 100% (2/2)        
2022-01-31T12:02:22.7494241Z remote: Compressing objects: 100% (2/2), done.        
2022-01-31T12:02:22.7495905Z remote: Total 5 (delta 2), reused 4 (delta 1), pack-reused 0        
2022-01-31T12:02:22.7556658Z From <hidden>
2022-01-31T12:02:22.7557957Z  + 696d35b...aafc6bf aafc6bf1ec658daaee9a4c186a4358c57e3e425b -> origin/ci  (forced update)
2022-01-31T12:02:22.7575647Z ##[endgroup]
2022-01-31T12:02:22.7577175Z ##[group]Determining the checkout info
2022-01-31T12:02:22.7579543Z ##[endgroup]
2022-01-31T12:02:22.7580172Z ##[group]Checking out the ref
2022-01-31T12:02:22.7583919Z [command]/usr/bin/git checkout --progress --force -B ci refs/remotes/origin/ci
2022-01-31T12:02:22.7616579Z Previous HEAD position was 5514fa6 Use unstable nixpkgs for good measure
2022-01-31T12:02:22.7624313Z Switched to a new branch 'ci'
2022-01-31T12:02:22.7625505Z Branch 'ci' set up to track remote branch 'ci' from 'origin'.
2022-01-31T12:02:22.7627661Z ##[endgroup]
2022-01-31T12:02:22.7664320Z [command]/usr/bin/git log -1 --format='%H'
2022-01-31T12:02:22.7688251Z 'aafc6bf1ec658daaee9a4c186a4358c57e3e425b'
2022-01-31T12:02:22.7809225Z ##[group]Run cachix/install-nix-action@v16
2022-01-31T12:02:22.7809620Z with:
2022-01-31T12:02:22.7809882Z ##[endgroup]
2022-01-31T12:02:22.8304499Z installer options: --no-channel-add --darwin-use-unencrypted-nix-store-volume --nix-extra-conf-file /tmp/tmp.6mYltXHyyS/nix.conf --daemon --daemon-user-count 16
2022-01-31T12:02:22.8350034Z   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2022-01-31T12:02:22.8350864Z                                  Dload  Upload   Total   Spent    Left  Speed
2022-01-31T12:02:22.8351132Z 
2022-01-31T12:02:22.8390794Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 68.183.23.220:443...
2022-01-31T12:02:22.8465402Z * Connected to nixos.org (68.183.23.220) port 443 (#0)
2022-01-31T12:02:22.8467427Z * ALPN, offering h2
2022-01-31T12:02:22.8468042Z * ALPN, offering http/1.1
2022-01-31T12:02:22.8468519Z * Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
2022-01-31T12:02:22.8511509Z * successfully set certificate verify locations:
2022-01-31T12:02:22.8512964Z *  CAfile: /etc/pki/tls/certs/ca-bundle.crt
2022-01-31T12:02:22.8513376Z *  CApath: none
2022-01-31T12:02:22.8513867Z * TLSv1.2 (OUT), TLS header, Certificate Status (22):
2022-01-31T12:02:22.8514241Z } [5 bytes data]
2022-01-31T12:02:22.8514594Z * TLSv1.2 (OUT), TLS handshake, Client hello (1):
2022-01-31T12:02:22.8514961Z } [512 bytes data]
2022-01-31T12:02:22.8604352Z * TLSv1.2 (IN), TLS handshake, Server hello (2):
2022-01-31T12:02:22.8605026Z { [94 bytes data]
2022-01-31T12:02:22.8672961Z * TLSv1.2 (IN), TLS handshake, Certificate (11):
2022-01-31T12:02:22.8673648Z { [3822 bytes data]
2022-01-31T12:02:22.8677279Z * TLSv1.2 (IN), TLS handshake, Server key exchange (12):
2022-01-31T12:02:22.8677677Z { [180 bytes data]
2022-01-31T12:02:22.8679322Z * TLSv1.2 (IN), TLS handshake, Server finished (14):
2022-01-31T12:02:22.8679714Z { [4 bytes data]
2022-01-31T12:02:22.8728401Z * TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
2022-01-31T12:02:22.8729197Z } [102 bytes data]
2022-01-31T12:02:22.8729875Z * TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
2022-01-31T12:02:22.8730248Z } [1 bytes data]
2022-01-31T12:02:22.8730594Z * TLSv1.2 (OUT), TLS handshake, Finished (20):
2022-01-31T12:02:22.8730942Z } [16 bytes data]
2022-01-31T12:02:22.8815585Z * TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
2022-01-31T12:02:22.9298834Z { [1 bytes data]
2022-01-31T12:02:22.9299685Z * TLSv1.2 (IN), TLS handshake, Finished (20):
2022-01-31T12:02:22.9300359Z { [16 bytes data]
2022-01-31T12:02:22.9301988Z * SSL connection using TLSv1.2 / ECDHE-ECDSA-AES256-GCM-SHA384
2022-01-31T12:02:22.9302648Z * ALPN, server accepted to use h2
2022-01-31T12:02:22.9303007Z * Server certificate:
2022-01-31T12:02:22.9303348Z *  subject: CN=*.nixos.org
2022-01-31T12:02:22.9303680Z *  start date: Jan 26 09:14:52 2022 GMT
2022-01-31T12:02:22.9303996Z *  expire date: Apr 26 09:14:51 2022 GMT
2022-01-31T12:02:22.9304609Z *  subjectAltName: host "nixos.org" matched cert's "nixos.org"
2022-01-31T12:02:22.9305178Z *  issuer: C=US; O=Let's Encrypt; CN=R3
2022-01-31T12:02:22.9305546Z *  SSL certificate verify ok.
2022-01-31T12:02:22.9306041Z * Using HTTP2, server supports multi-use
2022-01-31T12:02:22.9306720Z * Connection state changed (HTTP/2 confirmed)
2022-01-31T12:02:22.9307261Z * Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
2022-01-31T12:02:22.9307724Z } [5 bytes data]
2022-01-31T12:02:22.9308059Z * Using Stream ID: 1 (easy handle 0xfa65d0)
2022-01-31T12:02:22.9308389Z } [5 bytes data]
2022-01-31T12:02:22.9308681Z > GET /nix/install HTTP/2
2022-01-31T12:02:22.9308989Z > Host: nixos.org
2022-01-31T12:02:22.9309395Z > user-agent: curl/7.76.1
2022-01-31T12:02:22.9309690Z > accept: */*
2022-01-31T12:02:22.9309938Z > 
2022-01-31T12:02:22.9368614Z { [5 bytes data]
2022-01-31T12:02:22.9369416Z * Connection state changed (MAX_CONCURRENT_STREAMS == 4294967295)!
2022-01-31T12:02:22.9369879Z } [5 bytes data]
2022-01-31T12:02:22.9437506Z < HTTP/2 301 
2022-01-31T12:02:22.9438646Z < accept-ranges: bytes
2022-01-31T12:02:22.9439684Z < access-control-allow-origin: *
2022-01-31T12:02:22.9440155Z < age: 3295
2022-01-31T12:02:22.9440552Z < content-length: 0
2022-01-31T12:02:22.9440883Z < date: Mon, 31 Jan 2022 11:11:48 GMT
2022-01-31T12:02:22.9441185Z < server: Netlify
2022-01-31T12:02:22.9441512Z < via: 1.1 varnish, 1.1 varnish
2022-01-31T12:02:22.9442077Z < x-nf-request-id: 01FTR07G2N4E6QP4WJVHMNVHWQ
2022-01-31T12:02:22.9442604Z < x-cache: HIT, HIT
2022-01-31T12:02:22.9442987Z < x-cache-hits: 1, 1
2022-01-31T12:02:22.9443637Z < location: https://releases.nixos.org/nix/nix-2.6.0/install
2022-01-31T12:02:22.9444492Z < x-served-by: cache-iad-kcgs7200066-IAD, cache-ewr18124-EWR
2022-01-31T12:02:22.9445115Z < x-timer: S1643627508.456740,VS0,VE1
2022-01-31T12:02:22.9445405Z < 
2022-01-31T12:02:22.9445648Z { [0 bytes data]
2022-01-31T12:02:22.9445821Z 
2022-01-31T12:02:22.9446231Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2022-01-31T12:02:22.9446618Z * Connection #0 to host nixos.org left intact
2022-01-31T12:02:22.9447400Z * Issue another request to this URL: 'https://releases.nixos.org/nix/nix-2.6.0/install'
2022-01-31T12:02:22.9474586Z *   Trying 146.75.30.217:443...
2022-01-31T12:02:22.9496384Z * Connected to releases.nixos.org (146.75.30.217) port 443 (#1)
2022-01-31T12:02:22.9497193Z * ALPN, offering h2
2022-01-31T12:02:22.9498023Z * ALPN, offering http/1.1
2022-01-31T12:02:22.9498492Z * Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
2022-01-31T12:02:22.9541126Z * successfully set certificate verify locations:
2022-01-31T12:02:22.9542382Z *  CAfile: /etc/pki/tls/certs/ca-bundle.crt
2022-01-31T12:02:22.9542773Z *  CApath: none
2022-01-31T12:02:22.9543187Z * TLSv1.2 (OUT), TLS header, Certificate Status (22):
2022-01-31T12:02:22.9543557Z } [5 bytes data]
2022-01-31T12:02:22.9543909Z * TLSv1.2 (OUT), TLS handshake, Client hello (1):
2022-01-31T12:02:22.9544274Z } [512 bytes data]
2022-01-31T12:02:22.9569784Z * TLSv1.2 (IN), TLS handshake, Server hello (2):
2022-01-31T12:02:22.9570490Z { [102 bytes data]
2022-01-31T12:02:22.9570914Z * TLSv1.2 (IN), TLS handshake, Certificate (11):
2022-01-31T12:02:22.9571278Z { [2882 bytes data]
2022-01-31T12:02:22.9573049Z * TLSv1.2 (IN), TLS handshake, Server key exchange (12):
2022-01-31T12:02:22.9573792Z { [333 bytes data]
2022-01-31T12:02:22.9574355Z * TLSv1.2 (IN), TLS handshake, Server finished (14):
2022-01-31T12:02:22.9574756Z { [4 bytes data]
2022-01-31T12:02:22.9577636Z * TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
2022-01-31T12:02:22.9578381Z } [70 bytes data]
2022-01-31T12:02:22.9579041Z * TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
2022-01-31T12:02:22.9579414Z } [1 bytes data]
2022-01-31T12:02:22.9579761Z * TLSv1.2 (OUT), TLS handshake, Finished (20):
2022-01-31T12:02:22.9580107Z } [16 bytes data]
2022-01-31T12:02:22.9595451Z * TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
2022-01-31T12:02:22.9596123Z { [1 bytes data]
2022-01-31T12:02:22.9596792Z * TLSv1.2 (IN), TLS handshake, Finished (20):
2022-01-31T12:02:22.9597439Z { [16 bytes data]
2022-01-31T12:02:22.9598680Z * SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
2022-01-31T12:02:22.9599219Z * ALPN, server accepted to use h2
2022-01-31T12:02:22.9599584Z * Server certificate:
2022-01-31T12:02:22.9599980Z *  subject: CN=releases.nixos.org
2022-01-31T12:02:22.9600360Z *  start date: Aug 30 19:46:53 2021 GMT
2022-01-31T12:02:22.9600683Z *  expire date: Oct  1 19:46:52 2022 GMT
2022-01-31T12:02:22.9601398Z *  subjectAltName: host "releases.nixos.org" matched cert's "releases.nixos.org"
2022-01-31T12:02:22.9602222Z *  issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign Atlas R3 DV TLS CA H2 2021
2022-01-31T12:02:22.9602703Z *  SSL certificate verify ok.
2022-01-31T12:02:22.9603232Z * Using HTTP2, server supports multi-use
2022-01-31T12:02:22.9603677Z * Connection state changed (HTTP/2 confirmed)
2022-01-31T12:02:22.9604386Z * Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
2022-01-31T12:02:22.9604831Z } [5 bytes data]
2022-01-31T12:02:22.9605160Z * Using Stream ID: 1 (easy handle 0xfa65d0)
2022-01-31T12:02:22.9605498Z } [5 bytes data]
2022-01-31T12:02:22.9605921Z > GET /nix/nix-2.6.0/install HTTP/2
2022-01-31T12:02:22.9606308Z > Host: releases.nixos.org
2022-01-31T12:02:22.9606763Z > user-agent: curl/7.76.1
2022-01-31T12:02:22.9607057Z > accept: */*
2022-01-31T12:02:22.9607301Z > 
2022-01-31T12:02:22.9612016Z { [5 bytes data]
2022-01-31T12:02:22.9615305Z < HTTP/2 200 
2022-01-31T12:02:22.9616174Z < last-modified: Tue, 25 Jan 2022 00:33:38 GMT
2022-01-31T12:02:22.9616699Z < etag: "2163d46777c4214e1b759bd274ee1cba"
2022-01-31T12:02:22.9617181Z < content-type: text/plain
2022-01-31T12:02:22.9617521Z < server: AmazonS3
2022-01-31T12:02:22.9618054Z < access-control-allow-origin: *
2022-01-31T12:02:22.9618619Z < accept-ranges: bytes
2022-01-31T12:02:22.9618950Z < date: Mon, 31 Jan 2022 12:02:22 GMT
2022-01-31T12:02:22.9619252Z < via: 1.1 varnish
2022-01-31T12:02:22.9619508Z < age: 39362
2022-01-31T12:02:22.9620003Z < x-served-by: cache-iad-kiad7000026-IAD
2022-01-31T12:02:22.9620492Z < x-cache: HIT
2022-01-31T12:02:22.9620862Z < x-cache-hits: 2
2022-01-31T12:02:22.9621290Z < x-timer: S1643630543.961505,VS0,VE0
2022-01-31T12:02:22.9621719Z < content-length: 4046
2022-01-31T12:02:22.9622001Z < 
2022-01-31T12:02:22.9622242Z { [1146 bytes data]
2022-01-31T12:02:22.9622573Z 
2022-01-31T12:02:22.9622964Z 100  4046  100  4046    0     0  32111      0 --:--:-- --:--:-- --:--:-- 32111
2022-01-31T12:02:22.9623391Z * Connection #1 to host releases.nixos.org left intact
2022-01-31T12:02:22.9701151Z downloading Nix 2.6.0 binary tarball for x86_64-linux from 'https://releases.nixos.org/nix/nix-2.6.0/nix-2.6.0-x86_64-linux.tar.xz' to '/tmp/nix-binary-tarball-unpack.sT8DsjPZHm'...
2022-01-31T12:02:22.9745373Z   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2022-01-31T12:02:22.9745931Z                                  Dload  Upload   Total   Spent    Left  Speed
2022-01-31T12:02:22.9746497Z 
2022-01-31T12:02:23.0674496Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2022-01-31T12:02:23.0675144Z 100 27.2M  100 27.2M    0     0   296M      0 --:--:-- --:--:-- --:--:--  296M
2022-01-31T12:02:25.5538968Z Note: a multi-user installation is possible. See https://nixos.org/manual/nix/stable/installation/installing-binary.html#multi-user-installation
2022-01-31T12:02:25.5553079Z Warning: the flag --darwin-use-unencrypted-nix-store-volume
2022-01-31T12:02:25.5561838Z          is no longer needed and will be removed in the future.
2022-01-31T12:02:25.5562113Z 
2022-01-31T12:02:25.5562583Z [1;31mSwitching to the Multi-user Installer[0m
2022-01-31T12:02:25.5656891Z 
2022-01-31T12:02:25.5657801Z [34m---- oh no! --------------------------------------------------------------------
2022-01-31T12:02:25.5665132Z [0m[31mPlease do not run this script with root privileges. I will call sudo
2022-01-31T12:02:25.5665618Z when I need to.
2022-01-31T12:02:25.5666118Z [0m
2022-01-31T12:02:25.5672180Z [31mWe'd love to help if you need it.
2022-01-31T12:02:25.5672614Z 
2022-01-31T12:02:25.5673389Z You can open an issue at https://github.com/nixos/nix/issues
2022-01-31T12:02:25.5674234Z 
2022-01-31T12:02:25.5674777Z Or feel free to contact the team:
2022-01-31T12:02:25.5675647Z  - Matrix: #nix:nixos.org
2022-01-31T12:02:25.5676512Z  - IRC: in #nixos on irc.libera.chat
2022-01-31T12:02:25.5677546Z  - twitter: @nixos_org
2022-01-31T12:02:25.5678580Z  - forum: https://discourse.nixos.org
2022-01-31T12:02:25.6574858Z child_process.js:642
2022-01-31T12:02:25.6575451Z     throw err;
2022-01-31T12:02:25.6575753Z     ^
2022-01-31T12:02:25.6576021Z 
2022-01-31T12:02:25.6577113Z Error: Command failed: /opt/agent/runners/0df3c58fddaf4f2f7-1/_work/_actions/cachix/install-nix-action/v16/lib/install-nix.sh
2022-01-31T12:02:25.6577886Z     at checkExecSyncError (child_process.js:621:11)
2022-01-31T12:02:25.6578667Z     at Object.execFileSync (child_process.js:639:15)
2022-01-31T12:02:25.6579588Z     at Object.<anonymous> (/opt/agent/runners/0df3c58fddaf4f2f7-1/_work/_actions/cachix/install-nix-action/v16/lib/main.js:4:17)
2022-01-31T12:02:25.6580303Z     at Module._compile (internal/modules/cjs/loader.js:959:30)
2022-01-31T12:02:25.6580991Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
2022-01-31T12:02:25.6581559Z     at Module.load (internal/modules/cjs/loader.js:815:32)
2022-01-31T12:02:25.6582104Z     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
2022-01-31T12:02:25.6582734Z     at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
2022-01-31T12:02:25.6583270Z     at internal/main/run_main_module.js:17:11 {
2022-01-31T12:02:25.6583577Z   status: 1,
2022-01-31T12:02:25.6583837Z   signal: null,
2022-01-31T12:02:25.6584115Z   output: [ null, null, null ],
2022-01-31T12:02:25.6584371Z   pid: 18955,
2022-01-31T12:02:25.6584600Z   stdout: null,
2022-01-31T12:02:25.6584852Z   stderr: null
2022-01-31T12:02:25.6585077Z }
2022-01-31T12:02:25.6585403Z [0m
2022-01-31T12:02:25.6660838Z Post job cleanup.
2022-01-31T12:02:25.7502147Z [command]/usr/bin/git version
2022-01-31T12:02:25.7543671Z git version 2.32.0
2022-01-31T12:02:25.7573397Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2022-01-31T12:02:25.7603368Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2022-01-31T12:02:25.7885337Z [command]/usr/bin/git config --local --name-only --get-regexp <hidden>
2022-01-31T12:02:25.7908554Z <hidden>
2022-01-31T12:02:25.7915192Z [command]/usr/bin/git config --local --unset-all <hidden>
2022-01-31T12:02:25.7942731Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp <hidden> && git config --local --unset-all <hidden> || :
2022-01-31T12:02:25.8325537Z Cleaning up orphan processes

```

</details>

**Comment by domenkozar** [comment]
I'm afraid I can't do much without fixing the installer. We could patch the installer after it'd downloaded, but that's going to be a lot of pain.

**Comment by kubukoz** [comment]
I see. Thanks anyway :)
